export enum HtmlSelector {
  NARY_OL = 'ol.dsl-ol-nary',
  BINARY_LI = 'li.dsl-li-binary',
  NARY_LI = 'li.dsl-li-nary',
  LEAF_LI = 'li.dsl-li-leaf',
  WHEN_UL = 'ul.dsl-ul-when',
  BINARY_UL = 'ul.dsl-ul-binary',
  BINARYCHILD_UL = 'ul.dsl-ul-binary-child',
  UNARY_UL = 'ul.dsl-ul-unary',
  NARY_UL = 'ul.dsl-ul-nary',
  UNARY_LI = 'ul.dsl-li-unary',
  ITERABLE_UL = 'ul.dsl-ul-iterable',
  MULTIPLE_VALIDATIONS_OL = 'ol.dsl-multiple-validations',
  PERCENTAGE_VALUE_DIV = 'div.percentage-value',
  TOKEN_OPERATOR_SPAN = 'span.dsl-token-operator',
  TOKEN_FIELD_SPAN = 'span.dsl-token-field',
  TOKEN_UNKNOWN_SPAN = 'span.dsl-token-unknown',
  TOKEN_VALUE_SPAN = 'span.dsl-token-value',
  TOKEN_BINARY_SPAN = 'span.dsl-token-binary',
  TOKEN_WHEN_SPAN = 'span.dsl-token-when',
  TOKEN_THEN_SPAN = 'span.dsl-token-then',
  TOKEN_ELSE_SPAN = 'span.dsl-token-else',
  TOKEN_SINGLE_MAPPING_SPAN = 'span.dsl-token-single-mapping',
  TOKEN_NARY_SPAN = 'span.dsl-token-nary',
}
