export enum HtmlSelector {
  NARY_OL = 'ol.dsl-ol-nary',
  BINARY_LI = 'li.dsl-li-binary',
  NARY_LI = 'li.dsl-li-nary',
  LEAF_LI = 'li.dsl-li-leaf',
  WHEN_UL = 'ul.dsl-ul-when',
  BINARY_UL = 'ul.dsl-ul-binary',
  BINARYCHILD_UL = 'ul.dsl-ul-binary-child',
  UNARY_UL = 'ul.dsl-ul-unary',
  NARY_UL = 'ul.dsl-ul-nary',
  UNARY_LI = 'ul.dsl-li-unary',
  ITERABLE_UL = 'ul.dsl-ul-iterable',
  PERCENTAGE_VALUE_DIV = 'div.percentage-value',
  TOKEN_OPERATOR_SPAN = 'span.dsl-token-operator',
  TOKEN_FIELD_SPAN = 'span.dsl-token-field',
  TOKEN_UNKNOWN_SPAN = 'span.dsl-token-unknown',
  TOKEN_VALUE_SPAN = 'span.dsl-token-value',
  TOKEN_BINARY_SPAN = 'span.dsl-token-binary',
  TOKEN_WHEN_SPAN = 'span.dsl-token-when',
  TOKEN_THEN_SPAN = 'span.dsl-token-then',
  TOKEN_ELSE_SPAN = 'span.dsl-token-else',
  TOKEN_SINGLE_MAPPING_SPAN = 'span.dsl-token-single-mapping',
  TOKEN_NARY_SPAN = 'span.dsl-token-nary',
}

export enum HtmlClass {
  SPACE = '&nbsp;',
  APOS = '&apos;',
  CSS_VALIDATION_RULE = 'dsl-validation-rule',
  CSS_VALIDATE = 'dsl-token-validate',
  CSS_NARY = 'dsl-token-nary',
  CSS_WHEN = 'dsl-token-when',
  CSS_ELSE = 'dsl-token-else',
  CSS_THEN = 'dsl-token-then',
  CSS_SINGLE_MAPPING = 'dsl-token-single-mapping',
  CSS_MULTIPLE_MAPPING = 'dsl-token-multiple-mapping',
  CSS_TYPE_CONVERTER = 'dsl-token-type-converter',
  CSS_OPERATOR = 'dsl-token-operator',
  CSS_TEMPLATE_PARAM = 'dsl-token-template-param',
  CSS_VALUE = 'dsl-token-value',
  CSS_FIELD = 'dsl-token-field',
  CSS_UNKNOWN = 'dsl-token-unknown',

  CSS_LI_LEAF = 'dsl-li-leaf',
  CSS_LI_BINARY = 'dsl-li-binary',
  CSS_LI_UNARY = 'dsl-li-unary',
  CSS_LI_NARY = 'dsl-li-nary',

  CSS_UL_WHEN = 'dsl-ul-when',
  CSS_UL_BINARY = 'dsl-ul-binary',
  CSS_UL_UNARY = 'dsl-ul-unary',
  CSS_UL_ITERABLE = 'dsl-ul-iterable',

  CSS_OL_NARY = 'dsl-ol-nary',
  CSS_OL_MAPPING_NARY = 'dsl-ol-mapping-nary',
}
